const worksDataset = [
    // ==========================================
    // Visual (36명 x 2작품 = 72개)
    // ==========================================
    { id: 'V_kangminji_1', category: 'Visual', designer: '강민지', engName: 'KANG MINJI', title: 'Algorithm of Five Elements', desc: 'SNS에서 발생하거나 확산한 갈등 사례를 음양오행에 대응시켜 갈등의 흐름을 에너지의 순환 구조로 해석한다. 이를 통해 갈등을 단순히 감정적으로 소비되는 대상이 아닌, 변화하고 이동하는 흐름으로 인식하고자 한다. 또한 사건의 주체뿐만 아니라 사건 속에서 형성되고 변화하는 여론의 흐름을 살펴보며, 음양오행에서 기운의 불균형으로 나타나는 상극 관계에 빗대어 해석한다. 이를 통해 개인이 갈등의 흐름에서 한 발 떨어져 그 구조를 객관적으로 바라보고, 감정에 휩쓸리지 않고 이성적으로 이해할 수 있도록 하는 것을 목표로 한다.', thumbFile: 'pc_kangminji_p1.png', detailPrefix: 'pe_kangminji_p1', imagesCount: 2, email: 'cuttyrabbit0823@naver.com', insta: '@k__min._.g' },
    { id: 'V_kangminji_2', category: 'Visual', designer: '강민지', engName: 'KANG MINJI', title: '삐뚤펫둘', desc: '외형적인 이유만으로 버려지는 못난이 농산물과 수산물을 활용하여 펫푸드를 만드는 푸드 업사이클링 브랜드이다. 못난이 농수산물의 형태에서 착안한 \'삐뚤빼뚤\'과 강아지와 고양이를 위한 브랜드라는 의미를 담기 위해 \'pet\'과 숫자 \'둘\'을 합쳐 \'삐뚤펫둘\'이라는 이름을 만들었다. 패키지와 라벨에는 버려지는 자원에 대한 관심을 유도하고, 친근하고 유쾌한 브랜드 이미지를 전달하기 위해 농수산물을 모티프로 디자인한 캐릭터를 활용하였다. 이를 통해 소비자가 제품을 친근하게 접하면서도 버려지는 농수산물의 새로운 가치에 관심을 가질 수 있도록 하였다.', thumbFile: 'pc_kangminji_p2.png', detailPrefix: 'pe_kangminji_p2', imagesCount: 2, email: 'cuttyrabbit0823@naver.com', insta: '@k__min._.g' },
    
    { id: 'V_kangseonjin_1', category: 'Visual', designer: '강선진', engName: 'KANG SEONJIN', title: 'Digital Blackout', desc: 'Digital Blackout은 가짜 뉴스, 딥페이크, 악플 등 디지털 사회의 문제에 대응하여 아날로그적 삶의 감각을 회복하고자 하는 반문화 운동 단체이다. 펑크 운동의 저항 정신과 DIY 문화를 바탕으로 디지털 환경을 비판적으로 바라본다. 심볼은 웹페이지 오류 코드인 404에서 착안하여 디지털 사회에 의도적인 오류를 만들어낸다는 의미를 담았다. 또한 펑크 문화를 반영해 누구나 쉽게 그릴 수 있는 단순한 선형 구조로 제작하였다. 아날로그적 가치를 중요시하는 단체의 성격을 반영하여 직접 촬영한 이미지를 스캔, 조합하는 방식으로 그래픽을 전개하였다.', thumbFile: 'pc_kangseonjin_p1.png', detailPrefix: 'pe_kangseonjin_p1', imagesCount: 2, email: 'seonjing84@gmail.com', insta: '@seon._.jin04' },
    { id: 'V_kangseonjin_2', category: 'Visual', designer: '강선진', engName: 'KANG SEONJIN', title: 'HEXAGHETTI', desc: 'HEXAGHETTI는 버려지는 식품 부산물을 활용한 푸드업사이클링 브랜드이다. 다당류로 이루어진 식품 부산물을 가수분해하여 단당류 형태로 전환하고, 발효 과정을 거쳐 단백질을 축적한 바이오매스로 만든다. 이후 이를 분쇄하여 단백질 파우더로 가공하고, 대체 밀가루로 활용해 파스타를 제작한다. 브랜드명은 다당류와 단당류의 분자 구조에서 나타나는 육각형을 뜻하는 Hexa와 스파게티를 뜻하는 Ghetti를 결합한 이름이다. 식품 부산물이 다당류에서 단당류로 분해되는 과정에서 착안하여, 육각형의 분자 구조가 로고 전반에 암시적으로 드러나도록 디자인하였다.', thumbFile: 'pc_kangseonjin_p2.png', detailPrefix: 'pe_kangseonjin_p2', imagesCount: 2, email: 'seonjing84@gmail.com', insta: '@seon._.jin04' },
    
    { id: 'V_kangjuhyun_1', category: 'Visual', designer: '강주현', engName: 'KANG JUHYUN', title: '인지 기록 소거 본부 / 맞춤 기억 재설계 센터', desc: '본 프로젝트는 기억을 통제 가능한 데이터로 규정하는 두 가상 기관의 세계관을 시각화한 작업이다. 대상자의 고통스러운 기억을 영구 절제 및 포맷하는 \'인지 기록 소거 본부\'는 냉철한 보안 프로토콜과 표준 집행 매뉴얼의 형태로 서늘한 통제 시스템을 드러낸다. 반면 VVIP를 위해 기억을 정교하게 편집·재구성하는 \'맞춤 기억 재설계 센터(CMRC)\'는 고급스러운 컨시어지 서비스와 전문 기술 명세서가 결합된 가이드북으로 표현된다. 상반된 목적을 지닌 두 기관의 매뉴얼을 통해 기억 제어가 일상화된 가상 사회의 단면을 입체적으로 탐구한다.', thumbFile: 'pc_kangjuhyun_p1.png', detailPrefix: 'pe_kangjuhyun_p1', imagesCount: 2, email: 'kangjh0901@naver.com', insta: '@_jifdflo' },
    { id: 'V_kangjuhyun_2', category: 'Visual', designer: '강주현', engName: 'KANG JUHYUN', title: '녹 (NOK)', desc: '독립 출판 브랜드 \'녹(NOK)\'은 밤이라는 고유한 시간대에 몰입하는 심야 독서가를 위한 시각 아이덴티티 디자인 프로젝트이다. 본 프로젝트는 총 5권으로 구성된 총서 시리즈의 도서 표지와 아트 포스터, 브랜드 가이드북 전반을 아우른다. 고양이 캐릭터 \'노크\'와 이끼를 형상화한 \'모스\'를 활용한 서사를 더해 브랜드에 독창적인 활력을 부여하고, 섬세한 타이포그래피와 독립 서점의 아늑한 무드를 살린 시각 그래픽으로 완성도를 높였다. 독서라는 사적인 경험을 시각적 서사로 재해석하여 심야의 고요함과 문학적 감성을 담아낸 출판 브랜딩을 제안한다.', thumbFile: 'pc_kangjuhyun_p2.png', detailPrefix: 'pe_kangjuhyun_p2', imagesCount: 2, email: 'kangjh0901@naver.com', insta: '@_jifdflo' },
    
    { id: 'V_konayeon_1', category: 'Visual', designer: '고나연', engName: 'KO NAYEON', title: 'MY DAY', desc: '‘덕질’이라는 주제에서 출발해 오랫동안 좋아해 온 DAY6와 나 자신을 작업의 대상으로 삼았다. 2020년부터 2025년까지 DAY6를 좋아하며 달라진 일상과 감정, 행동 방식을 기록하고, 그 과정을 영상으로 풀어냈다. 처음에는 DAY6를 바라보는 관찰자였지만 점차 그들의 세계 안으로 들어가게 되는 과정을 총 6편의 에피소드로 구성하였으며, 스톱모션과 콜라주 기법을 활용해 눈에 보이지 않는 감정과 덕질이 일상에 미친 영향을 시각적으로 표현했다. 이러한 기록을 인포그래픽으로 확장해 시간에 따라 변화한 모습을 함께 기록했다.', thumbFile: 'pc_konayeon_p1.png', detailPrefix: 'pe_konayeon_p1', imagesCount: 2, email: 'konangnang.e@gmail.com', insta: '@na.yeoniy' },
    { id: 'V_konayeon_2', category: 'Visual', designer: '고나연', engName: 'KO NAYEON', title: 'SPEC', desc: 'SPEC은 카페인을 커피로 마시는 기존 방식에서 벗어나, 사용자의 필요에 따라 뿌리고 붙이고 먹고 씹는 형태로 확장한 기능성 라이프스타일 브랜드이다. 브랜드명 SPEC의 각 철자는 제품군과 연결되며, S는 Spray, P는 Patch, E는 Eat, C는 Chew를 의미한다. 로고는 각 제품의 특징을 반영한 레터링으로 제작해 브랜드 콘셉트를 강조하였다. 또한 레터링을 활용한 패턴을 패키지 전반에 적용해 시각적 포인트를 더하고, 펄지를 사용해 기능성과 확장성을 지닌 미래적인 브랜드 이미지를 표현하였다.', thumbFile: 'pc_konayeon_p2.png', detailPrefix: 'pe_konayeon_p2', imagesCount: 2, email: 'konangnang.e@gmail.com', insta: '@na.yeoniy' },
    
    { id: 'V_kongeunhee_1', category: 'Visual', designer: '공은희', engName: 'KONG EUNHEE', title: '동조의 흔적', desc: '동조가 실제로 작동했던 순간들을 사건, 소비, 언어 세 가지로 수집하고 그 흔적을 시각화한 프로젝트다. 보이지 않는 집단의 움직임을 탐구하며 \'동조\'라는 개념에 주목했고, 우리가 인식하지 못했던 사소한 동조들이 모여 하나의 사건이 되고 소비로 이어지는 순간들에 집중했다. 사건은 \'표면적 현상\'과 \'숨겨진 이면\'의 대조를 표현하고, 소비는 \'지면 광고\'의 시각 형식을 재해석하며, 언어는 카드 형식으로 제작했다. 이를 통해 동조가 우리의 일상에 어떤 영향을 미치는지 들여다보고 한 번 더 생각해 보는 계기를 만들고자 한다.', thumbFile: 'pc_kongeunhee_p1.png', detailPrefix: 'pe_kongeunhee_p1', imagesCount: 2, email: 'silverhappy04@gmail.com', insta: '@tor._rlo' },
    { id: 'V_kongeunhee_2', category: 'Visual', designer: '공은희', engName: 'KONG EUNHEE', title: 'PHYLOS', desc: 'PHYLOS는 식물의 종과 바다를 뜻하는 그리스어의 합성어로, 염생식물의 스스로 정화하는 기능에 주목한 바디케어 브랜드이다. 해홍나물, 갯질경, 나문재, 퉁퉁마디 네 가지 염생식물 추출물을 핵심 성분으로 세정과 동시에 피부 장벽을 건강하게 채우며 일상 속 새로운 바디케어 문화를 제안한다. 기존 코스메틱 분야의 전형적인 미니멀리즘에서 한 단계 더 확장하여, 극한의 자연환경을 견뎌낸 식물 고유의 유기적인 구조와 원초적 에너지를 직관적으로 강조한 그래픽으로 풀어내며 브랜드만의 생동감 있는 시각적 인상을 남기고자 한다.', thumbFile: 'pc_kongeunhee_p2.png', detailPrefix: 'pe_kongeunhee_p2', imagesCount: 2, email: 'silverhappy04@gmail.com', insta: '@tor._rlo' },
    
    { id: 'V_kimgayeon_1', category: 'Visual', designer: '김가연', engName: 'KIM GAYEON', title: 'WASTED CLUB', desc: '모든 낭비는 정말 나쁜 것일까? 우리는 효율과 생산성을 우선하는 사회를 살아가지만, 새로운 결과는 수많은 실패와 시행착오, 비효율적인 과정 속에서 만들어진다. 낭비는 단순한 손실이 아니라 경험과 가능성을 만들어내는 과정이며, 모든 시도는 결국 현재의 나를 만드는 자산이 된다. 이러한 메시지를 자유롭고 해방적인 클럽 문화로 재해석하여 음악, 포스터, 그래피티, 인쇄물, 굿즈 등을 통해 낭비를 즐기고 공유하는 가상의 클럽 공간을 구현한다. 목적 없는 행동과 비효율적인 과정 또한 삶을 풍요롭게 만드는 경험이 될 수 있음을 이야기한다.', thumbFile: 'pc_kimgayeon_p1.png', detailPrefix: 'pe_kimgayeon_p1', imagesCount: 2, email: 'maregayean4520@gmail.com', insta: '@gayoizz' },
    { id: 'V_kimgayeon_2', category: 'Visual', designer: '김가연', engName: 'KIM GAYEON', title: 'mare', desc: 'mare는 미래 식량이자 슈퍼푸드로 주목받는 미세조류를 바탕으로 지속 가능한 식물성 영양을 제안하는 브랜드이다. 스피루리나, 클로렐라, 두나리엘라가 가진 풍부한 영양 가치를 미세조류 분말, 영양 캡슐, 프로틴칩 등 일상 속 다양한 제품으로 풀어내어 보다 쉽고 맛있게 즐길 수 있는 형태로 선보인다. 미세조류가 가진 낯선 이미지를 다양한 제품과 시각적 경험으로 재해석하여 새로운 식문화의 이미지를 구축한다. 미세조류를 일상적인 식품과 영양 제품으로 자연스럽게 접할 수 있도록 하며, 건강과 지속 가능성을 함께 고려한 새로운 식문화의 가능성을 제시한다.', thumbFile: 'pc_kimgayeon_p2.png', detailPrefix: 'pe_kimgayeon_p2', imagesCount: 2, email: 'maregayean4520@gmail.com', insta: '@gayoizz' },
    
    { id: 'V_kimmiso_1', category: 'Visual', designer: '김미소', engName: 'KIM MISO', title: '돌아올 수 없는', desc: '사람은 언젠가 한 번은 돌이킬수없는 말을 내뱉곤 한다. 그것의 결과는 이별일수도 때론 새로운 관계의 시작이 될 수 도 있다. 이런 돌아올수없는 라는 말이 다시 떠올릴수록 특별하면서도 긍정적일수도 부정적일수도 있다는 모호한 점을 느껴 수집 및 시각화한다. 우선 설문을 통해 돌이킬 수 없는 말들에 대해 수집 후, 문장의 상황과 감정을 분류 및 시각화한 문장 포스터와 \'돌아올수없는\'이라는 말에 대한 모호한 감정과 여러 문장의 파편을 담아 메인 포스터로 구성된다. 또한 해당 그래픽을 기반으로 수집한 문장에 대한 아카이브북 형식의 책과 카드 등이 구성된다.', thumbFile: 'pc_kimmiso_p1.png', detailPrefix: 'pe_kimmiso_p1', imagesCount: 2, email: 'imsokim0308@gmail.com', insta: '@isoso7333' },
    { id: 'V_kimmiso_2', category: 'Visual', designer: '김미소', engName: 'KIM MISO', title: '막나이다', desc: '‘막나이다’는 액이 물러가길 바라는 간절한 ‘기원’에서 시작해 신비로운 힘(신기)을 빌려, 액운을 부수어 마셔 물리치는 가상의 액막이 음료 브랜드이다. 막나이다는 액막이 기원을 위해 \'막다\'와 \'비나이다\'를 합성했다. 각 분야를 관장하는 6명의 신(영등할매, 오늘이, 자청비, 칠성, 가믄장아기, 바리데기)으로부터 힘을 받아 6가지 맛으로 이루어져 있다. 이는 유독 운수가 나쁜 날, 소비자가 원하는 방향으로 액운을 물리칠 수 있게 하기 위함이다. 막나이다는 해당 신을 중심으로 메인 그래픽을 제작해 기본 사각팩 세트와 음료병 세트로 선보이고자 한다.', thumbFile: 'pc_kimmiso_p2.png', detailPrefix: 'pe_kimmiso_p2', imagesCount: 2, email: 'imsokim0308@gmail.com', insta: '@isoso7333' },
    
    { id: 'V_kimsoeun_1', category: 'Visual', designer: '김소은', engName: 'KIM SOEUN', title: 'Sopho Shop', desc: '흔히 \'중2병\'이라고 하면 흑역사이자 부끄러운 과거만으로 치부하고 잊고 싶어하는 경우가 많은데, 중2병도 그 시기만이 가진 깊은 몰입, 자신감 등의 강점들이 있는 만큼 부정적이지 않고 긍정적으로 인식될 수 있도록, 이 시기만의 강점을 시각적으로 재밌게 보여줘 중2병의 가치를 새롭게 알리는 브랜드이다. 중2병 시기에 있었던 다양한 사연들을 수집하고 이를 각색해 긍정적으로 강점을 돋보이게 보여주고자 했고, 사진을 직접 촬영해 나타내려 했다. 행동 양식 6가지를 각각 전달하는 포스터와 브랜드에서 판매하는 굿즈, 중2병 스토리를 보여주는 웹을 제작했다.', thumbFile: 'pc_kimsoeun_p1.png', detailPrefix: 'pe_kimsoeun_p1', imagesCount: 2, email: 'kimse041114@gmail.com', insta: '@_ssueno' },
    { id: 'V_kimsoeun_2', category: 'Visual', designer: '김소은', engName: 'KIM SOEUN', title: 'NIZ', desc: '최소 부피의 패키지를 메인으로 제공해 편리성과 실용성을 높인 동결건조 식품 브랜드이다. 메인 패키지인 약포지에 붙는 가장 작은 라벨 스티커는 가로 5cm, 세로 4cm의 작은 판형으로, 마이크로 타이포 작업을 보여주는 품목이다. 식품은 베리류, 단백질, 야채의 3가지 종류로 각각 2개의 식품을 제공한다. 베리류는 블루베리와 라즈베리, 단백질은 닭가슴살과 그릭요거트, 야채는 아스파라거스와 브로콜리를 제공하며 약포지, 봉투, 박스 3가지의 패키지로 최소 부피의 메인 품목인 약포지를 여러 묶음으로 제공한다.', thumbFile: 'pc_kimsoeun_p2.png', detailPrefix: 'pe_kimsoeun_p2', imagesCount: 2, email: 'kimse041114@gmail.com', insta: '@_ssueno' },
    
    { id: 'V_kimsua_1', category: 'Visual', designer: '김수아', engName: 'KIM SUA', title: 'PIBIP', desc: 'PIBI는 혐오를 공감으로 전환하는 문구 브랜드이다. 브랜드명은 ‘Peeve’s Inner Behind Insight’의 약자로, 짜증나는 사람들의 내면을 들여다본다는 의미를 담고 있다. 혐오 표현이 일상화된 시대에 서로를 이해하는 계기를 만들고자, 혐오의 대상이 되는 사람들을 10대부터 60대 이상까지 총 60종의 캐릭터로 디자인해 문구류로 시각화하였다. 또한 각 세대를 차원에 빗대어 선에서 시작해 실물로 확장되도록 표현하였다. 이를 통해 혐오 너머의 일상과 내면을 보여주고, 서로를 향한 시선이 이해와 공감으로 나아가는 경험을 전하고자 한다.', thumbFile: 'pc_kimsua_p1.png', detailPrefix: 'pe_kimsua_p1', imagesCount: 2, email: 'nellybell@naver.com', insta: '@wonderland_again' },
    { id: 'V_kimsua_2', category: 'Visual', designer: '김수아', engName: 'KIM SUA', title: 'LOW', desc: 'PLOW는 씨앗에서 시작된 식물성 식단을 담는 저탄소 도시락 브랜드이다. 브랜드명 PLOW는 Plant와 Flow의 합성어로, 식물성 식단으로 저탄소 생활이 자연스럽게 이루어진다는 의미를 담고 있다. 로고는 저탄소의 출발점인 씨앗과 새싹을 레터링에 반영해 디자인하였다. 또한 씨앗에서 시작되는 자연물을 7가지 카테고리로 나누어 심볼을 제작하고, 이를 바탕으로 7가지 도시락 메뉴를 구성하였다. 이와 함께 씨앗 봉투와 주스 등의 서브 상품과 포스터·리플렛·메시지 카드 등의 굿즈를 구성해 브랜드를 더욱 몰입감 있게 경험할 수 있도록 하였다.', thumbFile: 'pc_kimsua_p2.png', detailPrefix: 'pe_kimsua_p2', imagesCount: 2, email: 'nellybell@naver.com', insta: '@wonderland_again' },
    
    { id: 'V_kimyein_1', category: 'Visual', designer: '김예인', engName: 'KIM YEIN', title: '문장의 시각화', desc: '디자이너 50명의 각기 다른 칼럼을 시각적으로 재해석하여 두 가지 매체인 포스터와 책으로 제작하였다. 포스터는 각 칼럼의 핵심 내용과 분위기를 효과적으로 전달하기 위해 타이포그래피를 중심으로 시각화하였으며, 글의 특성과 의미에 따라 서체와 크기, 배치 등의 요소를 다르게 구성하였다. 책은 50명의 칼럼을 각각 하나의 소책자로 구성하고, 각 디자이너의 글과 내용에 맞춰 서로 다른 디자인을 적용하여 제작하였다. 두 매체는 동일한 칼럼을 기반으로 하되, 매체의 특성에 따라 각각 다른 방식으로 내용을 전달하고자 하였다.', thumbFile: 'pc_kimyein_p1.png', detailPrefix: 'pe_kimyein_p1', imagesCount: 2, email: 'kimseoduler@gmail.com', insta: '@kim_dobi_1201' },
    { id: 'V_kimyein_2', category: 'Visual', designer: '김예인', engName: 'KIM YEIN', title: '팔레토', desc: '팔레토는 한국의 각 지역을 배경으로 지역 특산물을 젤라토로 선보이는 오프라인 젤라토 브랜드이다. 총 20가지의 특산물을 선정하여 각 재료가 가진 고유한 맛과 특징을 제품에 담고, 이를 효과적으로 전달할 수 있도록 브랜드 아이덴티티와 패키지를 디자인하였다. 지역별 특산물의 차이를 그래픽에 반영하고, 각 젤라토의 특징을 시각적으로 구분할 수 있도록 패키 디자인을 구성하였다. 제품의 특성과 유통 환경을 고려하여 아이스 박스와 펄프 용기를 비롯한 패키지를 제작하고, 브랜드의 시각적 아이덴티티를 일관되게 적용하였다.', thumbFile: 'pc_kimyein_p2.png', detailPrefix: 'pe_kimyein_p2', imagesCount: 2, email: 'kimseoduler@gmail.com', insta: '@kim_dobi_1201' },
    
    { id: 'V_kimeunyoung_1', category: 'Visual', designer: '김은영', engName: 'KIM EUNYOUNG', title: '잔혹동화', desc: '그림형제의 잔혹동화 중 우리나라에 비교적 잘 알려지지 않은 다섯 편을 선정하여 성인을 위한 동화책 시리즈로 재해석하였다. 어린이 동화의 밝고 친근한 이미지에서 벗어나 원작이 가진 잔혹함과 기묘한 분위기를 시각적으로 표현하고자 하였다. 삽화는 사실적인 묘사보다 단순한 형태와 면을 활용한 현대적인 그래픽으로 구성하였으며, 각 이야기의 분위기에 어울리는 제한된 컬러를 사용하였다. 또한 다섯 권이 하나의 시리즈로 보일 수 있도록 일관된 표현 방식을 적용하여 그림형제 원작 특유의 어둡고 낯선 분위기를 전달한다.', thumbFile: 'pc_kimeunyoung_p1.png', detailPrefix: 'pe_kimeunyoung_p1', imagesCount: 2, email: 'naanaeun228@naver.com', insta: '@euny228' },
    { id: 'V_kimeunyoung_2', category: 'Visual', designer: '김은영', engName: 'KIM EUNYOUNG', title: '삼시내끼', desc: '삼시내끼는 서로 다른 식사 스타일을 가진 사람들을 위한 커스텀 도시락 브랜드이다. 하루 세 끼를 정해 먹는 것이 일반적이지만, 바쁜 일상 속에서 매 끼니를 제때 챙기기는 쉽지 않다. 운동이나 체중 조절 등 생활 방식에 따라 필요한 영양소와 식사 루틴에도 차이가 생긴다. 삼시내끼는 이러한 차이에 주목해 정해진 식사 방식에 자신을 맞추는 대신, 각자의 식사 스타일에 따라 한 끼를 직접 구성할 수 있도록 한다. 끼니의 횟수와 필요한 영양소를 고려해 식사를 선택하고 조절하며, 정해진 틀에서 벗어나 나만의 식사 구조를 만들어 가는 방식을 제안한다.', thumbFile: 'pc_kimeunyoung_p2.png', detailPrefix: 'pe_kimeunyoung_p2', imagesCount: 2, email: 'naanaeun228@naver.com', insta: '@euny228' },
    
    { id: 'V_kimeunji_1', category: 'Visual', designer: '김은지', engName: 'KIM EUNJI', title: '봉그다', desc: '봉그다는 해녀와의 협업을 통해 진행하며 해양환경을 보호하는 브랜드다. 해녀가 바다를 삶의 터전으로 삼아온 방식과 해양 정화 활동인 플로빙을 연결해, 바다를 즐기는 동시에 바다를 지키는 문화를 만들어 나간다. 해녀와 플로빙을 직관적인 픽토그램으로 표현해 브랜드의 활동성과 바다의 이미지를 시각적으로 담아냈으며, 이를 봉그다의 브랜드 이야기와 가치를 전달했다. 또한 해녀의 활동과 플로빙이라는 현대적인 실천을 하나의 시각 언어로 연결하여, 바다를 단순히 소비하는 공간이 아닌 함께 보호해야 할 공간으로 바라보는 브랜드의 방향성을 표현했다.', thumbFile: 'pc_kimeunji_p1.png', detailPrefix: 'pe_kimeunji_p1', imagesCount: 2, email: 'purple0301@naver.com', insta: '@431eunji' },
    { id: 'V_kimeunji_2', category: 'Visual', designer: '김은지', engName: 'KIM EUNJI', title: '키누', desc: '키누는 미래의 환경 변화와 식량 문제에 주목해, 우주 식품의 장기 보존 기술에서 영감을 받아 기획한 미래 식량 브랜드다. 제한된 환경에서도 식품을 안정적으로 보관하고 간편하게 섭취할 수 있도록 실용성과 휴대성을 고려했으며, 이를 미래적인 패키 디자인으로 시각화했다. 카레맛, 쇠고기맛, 훈제 바비큐맛, 매운 고기맛, 크림치즈맛의 스파우치 팩을 비롯해 블리스터 팩과 지퍼백, 리플렛을 제작했다. 각 맛의 특징을 반영한 굿즈까지 함께 구성해 키누만의 미래 식량 문화를 하나의 브랜드 경험으로 확장했다.', thumbFile: 'pc_kimeunji_p2.png', detailPrefix: 'pe_kimeunji_p2', imagesCount: 2, email: 'purple0301@naver.com', insta: '@431eunji' },
    
    { id: 'V_kimjiyeon_1', category: 'Visual', designer: '김지연', engName: 'KIM JIYEON', title: '익숙한 듯 낯선', desc: '익숙한 듯 낯선은 청각장애인의 소통 방식 중 문자 수어를 활용한 타이포그래피 프로젝트이다. 같은 공간에 살지만 소통 방식이 달라지면 익숙한 환경도 낯설게 느껴질 수 있다는 점에서 출발한다. 수어의 손 모양과 동작을 바탕으로 자음·모음·숫자의 형태를 변형하고 재해석하는 실험을 진행하며 청각장애인이 겪는 소통의 어려움은 포스터에 담는다. 문자 수어를 익힐 수 있도록 3D 문자 카드와 따라 쓰는 책자를 제작하고, 손의 움직임을 탐색하는 체험형 웹으로 확장한다. 이를 통해 문자 수어의 형태와 움직임을 직접 체험하며 청각장애인의 소통 방식을 이해하도록 한다.', thumbFile: 'pc_kimjiyeon_p1.png', detailPrefix: 'pe_kimjiyeon_p1', imagesCount: 2, email: 'jiiyeoxn@gmail.com', insta: '@jiiye.n_' },
    { id: 'V_kimjiyeon_2', category: 'Visual', designer: '김지연', engName: 'KIM JIYEON', title: '생선생', desc: '생선생은 \'생선\'과 \'선생\'을 합친 언어유희에서 출발한 자취생을 위한 초간편 수산물 브랜드이다. 생선 요리를 먹고 싶어도 비린내와 복잡한 조리 과정 때문에 쉽게 시도하지 못하는 자취생이 간편하게 한 끼를 즐기며, \'나도 생선 요리를 할 수 있다\'는 자신감을 가질 수 있도록 한다. 로고는 유연하게 헤엄치는 물고기 몸통 안에 생선생 레터링을 넣어 하나의 물고기 형상으로 완성한다. 집밥 선생 캐릭터를 더해 친근한 이미지를 만들고, 구이 띠지와 조림 박스, 순살 큐브 도시락, 양념 밀키트에는 파도 그래픽을 일관되게 적용해 패키지 전체의 통일감을 높인다.', thumbFile: 'pc_kimjiyeon_p2.png', detailPrefix: 'pe_kimjiyeon_p2', imagesCount: 2, email: 'jiiyeoxn@gmail.com', insta: '@jiiye.n_' },
    
    { id: 'V_kimjio_1', category: 'Visual', designer: '김지오', engName: 'KIM JIO', title: '사이버 렉카로 인해 만들어진 악플들', desc: '현대 미디어 생태계에서 사이버 렉카는 자극적인 편집과 확증 편향을 동력 삼아 대중의 집단적 언어폭력을 유도한다. 가해자에게는 찰나의 가벼운 유희에 불과한 댓글일지라도, 피해자에게는 한 개인의 일상을 무너뜨리는 실존적인 위협이자 파괴적인 정신적 타격으로 고스란히 전이된다. 본 작품은 사이버 렉카의 왜곡된 프레임과 대중의 무비판적인 낙인찍기가 낳은 집단 언어폭력의 실체를 시각화한다. 디지털 공간에 만연한 가벼운 유희 뒤에 가려진 파괴적인 폭력성과 그로 인해 남겨진 보이지 않는 상흔을 다각도로 드러낸다.', thumbFile: 'pc_kimjio_p1.png', detailPrefix: 'pe_kimjio_p1', imagesCount: 2, email: 'jio630411@gmail.com', insta: '@wldh03' },
    { id: 'V_kimjio_2', category: 'Visual', designer: '김지오', engName: 'KIM JIO', title: 'everbite', desc: 'everbite는 \'늘 곁에 있는 간식\'이라는 브랜드 철학 아래 플랑크톤을 활용해 언제 어디서나 건강하고 간편하게 즐기는 고지방 저탄수화물 키토 스낵 브랜드이다. 생소하게 느껴질 수 있는 미래 대체 자원인 플랑크톤을 친근하고 매력적인 일상의 식경험으로 전환하여, 지속 가능한 건강 라이프스타일의 확장을 지향한다. 과자, 바, 분말 쉐이크로 이어지는 3가지 제품군에 다채로운 맛을 조화롭게 결합하였으며, 환경과 건강을 동시에 생각하는 브랜드의 지속 가능한 가치를 통일감 있는 그래픽 디자인으로 구현했다.', thumbFile: 'pc_kimjio_p2.png', detailPrefix: 'pe_kimjio_p2', imagesCount: 2, email: 'jio630411@gmail.com', insta: '@wldh03' },
    
    { id: 'V_parkseoyeon_1', category: 'Visual', designer: '박서연', engName: 'PARK SEOYEON', title: '노동가치진흥원', desc: '노동가치진흥원(Invisible Labor Value Agency / ILVA)은 현행 국민계정 체계에서 측정되지 않는 비가시적 노동의 실태를 조사·기록·공표하기 위해 2027년 설립된 가상의 국가기관이다. 가사·돌봄·감정·인지·정체성·디지털 노동 등 공식 통계의 언어가 닿지 않는 노동 범주들을 다루며, 이를 가시화하고 사회적 논의의 대상으로 만드는 것을 목적으로 한다. 본원은 연간 실태 보고 간행물 《노동의 넓이》를 비롯해 웹사이트, 리플렛, 포스터 등 다양한 매체를 통해 비가시적 노동의 존재를 기록한다.', thumbFile: 'pc_parkseoyeon_p1.png', detailPrefix: 'pe_parkseoyeon_p1', imagesCount: 2, email: 'p.swim.youth@gmail.com', insta: '@5eo.y30n' },
    { id: 'V_parkseoyeon_2', category: 'Visual', designer: '박서연', engName: 'PARK SEOYEON', title: 'EveryWhey', desc: 'EveryWhey는 유청(Whey) 업사이클링 스킨케어 브랜드이다. 낙농 공정에서 발생하는 부산물인 유청을 화장품 성분으로, 동시에 PHB 바이오플라스틱 용기로 재활용하는 완전 순환 구조를 제안한다. 유청 속 젖산과 단백질은 피부 각질 케어와 장벽 강화에 실질적으로 작용하며, 유청 유래 PHB 바이오플라스틱 용기는 사용 후 완전 생분해된다. 유청을 화장품 성분과 용기에 동시에 적용함으로써 하나의 자원이 다양한 형태로 재활용될 수 있음을 보여주며, 환경적 가치와 제품의 기능적 가치를 함께 전달하는 지속가능한 브랜드를 지향한다.', thumbFile: 'pc_parkseoyeon_p2.png', detailPrefix: 'pe_parkseoyeon_p2', imagesCount: 2, email: 'p.swim.youth@gmail.com', insta: '@5eo.y30n' },
    
    { id: 'V_parkseohyun_1', category: 'Visual', designer: '박서현', engName: 'PARK SEOHYUN', title: 'NEAR', desc: '니어(NEAR)는 남극과 해양을 연구하며 지구 파괴의 원인을 역추적하는 미래의 가상 기업이다. 이들은 과거 인류, 즉 현재의 우리를 피의자로 지목하여 생태 파괴의 증거를 수집한다. 본 프로젝트는 이러한 설정을 바탕으로 훼손된 해양 생물 데이터와 환경 오염 조사 보고서를 시각 자료로 재구성하였다. 특히 미세 플라스틱 축적과 수온 상승 등 극심한 환경 변화로 인해 신체 구조가 기형적으로 변해버린 해양 생물들을 그래픽으로 디자인하여 사태의 심각성을 직관적으로 드러냈다. 이를 통해 인류의 무분별한 행동이 초래한 결과를 돌아보게 된다.', thumbFile: 'pc_parkseohyun_p1.png', detailPrefix: 'pe_parkseohyun_p1', imagesCount: 2, email: 'sh784669@gmail.com', insta: '@se.0hh' },
    { id: 'V_parkseohyun_2', category: 'Visual', designer: '박서현', engName: 'PARK SEOHYUN', title: '떠리', desc: '떠리(Thirty)는 과일, 빵, 유제품 등 유통기한이 얼마 남지 않은 음식을 소비자가 직접 골라 픽업하는 앱 서비스이다. 버려지기 직전이 가장 맛있게 잘 익은 순간이라는 생각에서 출발하여, 보통의 떨이 상품이 주는 낡고 저렴한 이미지를 벗겨내고 음식 본래의 신선한 매력을 살리는 데 초점을 맞췄다. 브랜드의 시각적 정체성은 마트의 마감 할인 스티커가 여러 장 겹쳐 붙은 모습에서 아이디어를 얻어 직관적으로 디자인하였다. 본 프로젝트는 낭비되는 음식을 줄이는 친환경 가치를 전하며, 일상에서 쉽게 실천하는 알뜰한 소비 방식을 이끈다.', thumbFile: 'pc_parkseohyun_p2.png', detailPrefix: 'pe_parkseohyun_p2', imagesCount: 2, email: 'sh784669@gmail.com', insta: '@se.0hh' },
    
    { id: 'V_parkyeonji_1', category: 'Visual', designer: '박연지', engName: 'PARK YEONJI', title: 'Dissolution Of Office', desc: '규격화된 사무용 문서와 시스템을 유연하게 해체하고 재조합하여, 시각적 해방감을 제시하는 가상의 오피스다. 효율과 규칙이 우선시되는 경직된 업무 환경 속에서 시각적 일탈을 통해 자유로움을 모색했다. 이를 위해 실제 기업의 시스템 구조를 분석하고, 기존의 매뉴얼을 비틀어 다르게 적용하는 해체 매뉴얼을 새롭게 구축했다. 수직적인 문서 양식과 규율을 다각도로 변형하고 획일적인 틀을 벗어난 시각 요소로 공간을 채웠다. 이를 통해 일상적인 직장을 유연한 공간으로 재구성하고, 기존과는 완전히 다른 새로운 시스템을 제안한다.', thumbFile: 'pc_parkyeonji_p1.png', detailPrefix: 'pe_parkyeonji_p1', imagesCount: 2, email: 'yeonji232303@gmail.com', insta: '@_yeonzi_' },
    { id: 'V_parkyeonji_2', category: 'Visual', designer: '박연지', engName: 'PARK YEONJI', title: 'somo', desc: '모든 것이 빠르게 소비되는 현대 사회에서, 온전히 나만을 위해 천천히 시간을 보내는 일은 점차 사라지고 있다. somo는 향을 통해 일상의 속도를 늦추기를 제안하며, 인센스와 향초를 단순한 제품이 아닌 고유한 시간 경험의 매개로 바라보는 브랜드다. 향이 타들어가는 시간과 그에 맞는 느린 행위를 큐레이션하여 제공하며, 인센스의 길이가 길어질수록 제안하는 여유의 시간도 함께 늘어난다. 향의 길이에 비례해 느림의 시간이 점진적으로 확장되는 브랜드 구조를 심볼 \'S\'의 유연한 형태 변형을 통해 직관적으로 시각화했다.', thumbFile: 'pc_parkyeonji_p2.png', detailPrefix: 'pe_parkyeonji_p2', imagesCount: 2, email: 'yeonji232303@gmail.com', insta: '@_yeonzi_' },
    
    { id: 'V_sonseojin_1', category: 'Visual', designer: '손서진', engName: 'SON SEOJIN', title: '대한민국 지역 우표 포스터 시리즈', desc: '우표를 가장 작은 단위의 포스터로 정의하고, 이를 대형 포스터로 확장하여 대한민국 각 지역의 정보를 전달하는 시리즈 작업이다. 우표의 형식적 요소들을 재구성하여 각 지역의 특징을 그래픽으로 나타낸다. 액면가는 전화 지역번호, 발행국은 KOREA, 발행연도는 2026, 지역명은 영문 표기로 대체하여 주요 디자인 요소로 활용한다. 우표 크기에서 출발하여 A4, A3, A2, A1 규격으로 단계별 확대 전개함으로써, 익숙한 우표 형태를 활용해 대한민국 지역 정보를 다채로운 포스터 시리즈로 구성한다.', thumbFile: 'pc_sonseojin_p1.png', detailPrefix: 'pe_sonseojin_p1', imagesCount: 2, email: 'jiniee61@naver.com', insta: '' },
    { id: 'V_sonseojin_2', category: 'Visual', designer: '손서진', engName: 'SON SEOJIN', title: '오직 식물성 아이스크림', desc: '오직\'은 말 그대로 식물성 재료만을 사용하여 만든 비건 아이스크림 브랜드이다. 유제품 없이도 아이스크림 본연의 부드러움을 구현하기 위해 쌀, 검은콩, 캐슈넛, 오트, 아몬드, 코코넛까지 총 6가지 자연 원료를 베이스로 삼았다. 브랜드 로고는 아이스크림을 스쿱으로 떠낸 모양 안에 \'오직\'이라는 활자를 배치하여 나타내었다. 로고 형태와 원료의 특징을 바탕으로 패키지 디자인과 브랜드 시각 요소를 구성하여 담백하고 직관적인 브랜드 디자인 이미지를 전달한다. 원료 본연의 맛을 다채롭게 살려 비건도 다양하고 풍성하게 즐길 수 있다.', thumbFile: 'pc_sonseojin_p2.png', detailPrefix: 'pe_sonseojin_p2', imagesCount: 2, email: 'jiniee61@naver.com', insta: '' },
    
    { id: 'V_aneunsu_1', category: 'Visual', designer: '안은수', engName: 'AN EUNSU', title: 'Flow', desc: 'Flow는 인간이 깊게 집중하는 순간이 단순한 목표 달성을 위한 집중이 아니라, 스스로 선택하고 좋아하는 활동을 즐기는 과정에서 자연스럽게 발생한다는 관점에서 출발한 프로젝트이다. 몰입이 형성되고 깊어지는 과정을 다섯 단계로 나누어 시리즈 포스터로 시각화하고, 25명을 대상으로 진행한 설문조사를 통해 몰입의 공통점과 차이점을 책으로 정리하고 시각화했다. 또한 웹사이트에서는 웹캠을 활용해 시선, 표정, 자세, 손의 움직임, 클릭 등에 반응하는 인터랙션을 구현하여 사용자가 직접 몰입의 과정을 경험하도록 구성했다.', thumbFile: 'pc_aneunsu_p1.png', detailPrefix: 'pe_aneunsu_p1', imagesCount: 2, email: 'esa5758@naver.com', insta: '@anunsuu' },
    { id: 'V_aneunsu_2', category: 'Visual', designer: '안은수', engName: 'AN EUNSU', title: 'Digging', desc: 'Digging은 흙이 묻고 울퉁불퉁한 외형 때문에 익숙하지 않게 느껴지는 뿌리채소의 숨겨진 가치를 발견하고 재해석한 식품 브랜드 프로젝트이다. 뿌리채소를 반으로 가르면 드러나는 예상치 못한 색과 형태, 맛의 대비에 주목하여 브랜드의 핵심 콘셉트로 설정했다. 브랜드명은 땅속에 숨겨진 재료의 새로운 매력을 발견한다는 의미를 담았으며, 로고 디자인은 뿌리채소의 울퉁불퉁한 겉모습을 형상화해 디자인했다. 우베, 파스닙, 야콘, 카사바를 활용한 스프레드, 건조 스낵, 스무디, 케이크와 아이스크림, 쇼핑백, 리플릿, 엽서 등으로 브랜드를 구성했다.', thumbFile: 'pc_aneunsu_p2.png', detailPrefix: 'pe_aneunsu_p2', imagesCount: 2, email: 'esa5758@naver.com', insta: '@anunsuu' },
    
    { id: 'V_yangjunpyo_1', category: 'Visual', designer: '양준표', engName: 'YANG JUNPYO', title: 'Future Seen Twice', desc: '평소 즐겨 듣던 음악 장르인 신스웨이브에서 출발한 작업이다. 신스웨이브는 과거 사람들이 상상했던 미래의 모습을 음악과 시각적 이미지로 표현하는 장르이다. 과거의 시점에서 바라본 미래가 오늘날 현실이 된 것처럼, 현재의 우리는 AI 기술이 빠르게 발전하는 시대를 살아가고 있다. 이러한 변화 속에서 지금의 시점에서 미래를 다시 상상한다면 어떤 모습으로 나타날지에 주목했다. 익숙한 신스웨이브의 미래적 이미지에 현재의 AI 기술과 감각을 결합하여, 과거의 미래관을 다시 해석하고 앞으로 다가올 미래의 모습을 표현하고자 한다.', thumbFile: 'pc_yangjunpyo_p1.png', detailPrefix: 'pe_yangjunpyo_p1', imagesCount: 2, email: 'hello0a0aa0@gmail.com', insta: '@0a0aa0_' },
    { id: 'V_yangjunpyo_2', category: 'Visual', designer: '양준표', engName: 'YANG JUNPYO', title: '양초장 Herbrewery', desc: '양초장 Herbrewery는 평소 막걸리를 즐기면서도 건강까지 함께 챙기고 싶다는 생각에서 시작한 브랜드이다. 약초와 막걸리를 결합하여 약초가 가진 다소 낯선 이미지를 계절의 향과 풍미를 담은 막걸리로 재해석한다. 또한 흔히 접하는 막걸리 병 대신 캔 형태를 적용하여 휴대성과 접근성을 높이고, 젊은 소비자들도 부담 없이 즐길 수 있는 새로운 전통주 브랜드를 만들고자 한다. 계절마다 다른 약초와 재료를 활용해 각기 다른 맛과 향을 경험할 수 있도록 구성하여, 전통주에 대한 새로운 인식을 제안하고 일상 속에서 자연스럽게 즐길 수 있는 브랜드를 지향한다.', thumbFile: 'pc_yangjunpyo_p2.png', detailPrefix: 'pe_yangjunpyo_p2', imagesCount: 2, email: 'hello0a0aa0@gmail.com', insta: '@0a0aa0_' },
    
    { id: 'V_ohjihye_1', category: 'Visual', designer: '오지혜', engName: 'OH JIHYE', title: '미제출', desc: '미제출', thumbFile: 'pc_ohjihye_p1.png', detailPrefix: 'pe_ohjihye_p1', imagesCount: 2, email: '미제출', insta: '' },
    { id: 'V_ohjihye_2', category: 'Visual', designer: '오지혜', engName: 'OH JIHYE', title: '미제출', desc: '미제출', thumbFile: 'pc_ohjihye_p2.png', detailPrefix: 'pe_ohjihye_p2', imagesCount: 2, email: '미제출', insta: '' },
    
    { id: 'V_yugayeong_1', category: 'Visual', designer: '유가영', engName: 'YU GAYEONG', title: '현대인을 맛있게 만드는 법 - 대한생체교', desc: '창세기에는 인간이 흙으로 빚어졌다는 이야기가 나온다. 땅에서 자라나는 채소도 인간처럼 흙에서 생겨나 숨을 쉬며 살아간다. 이 프로젝트는 일상에서 자주 쓰는 \'채소의 숨이 죽었다\'라는 표현을 지친 현대인의 모습에 겹쳐 보며 시작되었다. 숨 막히는 사회를 살아가느라 생기를 잃고 시들어버린 사람들을 채소에 빗대어 보고, 그들이 원래 지니고 있던 파릇파릇한 숨을 다시금 불어넣어 구원하고자 했다. 메마른 일상 속 시든 채소 같은 현대인들의 꺼져가는 숨을 다시 깨우고 잃어버린 생명력을 온전히 되돌려 구원하는 가상의 종교 프로젝트다.', thumbFile: 'pc_yugayeong_p1.png', detailPrefix: 'pe_yugayeong_p1', imagesCount: 2, email: 'rkdud041@naver.com', insta: '@g0o_zer0' },
    { id: 'V_yugayeong_2', category: 'Visual', designer: '유가영', engName: 'YU GAYEONG', title: 'Q, B, E', desc: 'Q, B, E\'는 환자용 파우더식을 요즘의 생활 방식에 맞게 다시 풀어내 대중에게 다가가는 브랜드다. 환자들만 먹는 음식이라는 무겁고 조심스러운 편견을 벗겨내고, 누구나 일상에서 부담 없이 마실 수 있도록 감각적인 형태로 담아냈다. 이를 통해 환자식을 낯설게 느끼던 시선을 친근하게 돌려놓고, 좁고 한정적이었던 환자용 파우더식의 세계를 더 넓은 영역으로 확장하고자 했다. 나아가 바쁜 하루 속에서 밥 한 끼 제대로 챙기기 힘든 사람들에게 언제 어디서나 고른 영양을 채울 수 있는 가벼운 대안을 건네며, 생활 속에 스며드는 새로운 식문화를 제안한다.', thumbFile: 'pc_yugayeong_p2.png', detailPrefix: 'pe_yugayeong_p2', imagesCount: 2, email: 'rkdud041@naver.com', insta: '@g0o_zer0' },
    
    { id: 'V_yooyoungwon_1', category: 'Visual', designer: '유영원', engName: 'YOO YOUNGWON', title: '소녀 88 프로젝트', desc: '소녀 88 프로젝트는 창작물과 미디어에서 다뤄지는 소녀 88명을 수집하고 분석하는 프로젝트이다. 결과물은 평면 매체인 포스터 88장과 입체 매체인 책 88권으로 구성되며, 서로 다른 물성을 통해 다양한 감각으로 작품을 경험하도록 했다. 창작물을 소설/음반/영화·드라마/만화 네 가지로 분류하고, 각 분야별 22명의 소녀를 선정했다. 포스터는 창작물의 소재, 대사, 설정을 변형하고 재해석해 디자인했으며, 책은 작품 속 설정을 재해석해 제작했다. 프로젝트는 미디어 속 정형화된 소녀를 재해석함으로써 각 소녀의 특색을 이해하고 감상하는 것을 목적으로 한다.', thumbFile: 'pc_yooyoungwon_p1.png', detailPrefix: 'pe_yooyoungwon_p1', imagesCount: 2, email: 'forxvxr8@gmail.com', insta: '@forxvxr8' },
    { id: 'V_yooyoungwon_2', category: 'Visual', designer: '유영원', engName: 'YOO YOUNGWON', title: 'UNCUT JAM', desc: 'UNCUT JAM은 유기농 못난이 과일을 활용한 잼 브랜드로, 가공되지 않아 더욱 가치 있는 못난이 과일을 보석으로 표현했다. 과일은 딸기, 레몬, 구아바, 포도, 복숭아, 사과 총 6가지로 구성했다. 과일을 보석으로 형상화한 그래픽을 중심으로 잼 라벨, 패키지, 리플렛을 디자인했다. 구성품은 380g 유리병 잼과 20g 스틱잼으로 이루어지며, 패키지는 보석이라는 브랜드 정체성을 살려 선물처럼 열어볼 수 있는 지기구조로 제작했다. 라벨과의 통일성을 위해 패키지 윗면과 옆면에도 보석 그래픽을 배치했으며, 보석 과일 그래픽을 활용한 굿즈도 제작했다.', thumbFile: 'pc_yooyoungwon_p2.png', detailPrefix: 'pe_yooyoungwon_p2', imagesCount: 2, email: 'forxvxr8@gmail.com', insta: '@forxvxr8' },
    
    { id: 'V_yoonsieon_1', category: 'Visual', designer: '윤시언', engName: 'YOON SIEON', title: '어린이 예절 카드 "예절 친구들"', desc: '예절 친구들은 \'요즘 아이들은 예의가 없다\' 문장을 떠올리며 시작한 프로젝트로 아이들이 쉽게 예의를 배우고 따라 할 수 있도록 카드의 형태로 제작하였다. 카드는 총 10가지의 핵심 예절을 선정 후 핵심 예절의 주제에 맞춰 10장의 카드씩 총 100장을 제작하였다. 인사하기, 부착하기, 감사하기, 사과하기, 시선 보기, 경청하기, 식사 예절, 함께하는 생활, 허락받기, 약속과 시간 등으로 아이들이 배울 수 있는 행동을 가르친다. 아이들은 이것을 보고 따라 하기도 하며 경험을 쌓으며 이후 배운 예의를 실천하는 것을 목적으로 프로젝트를 진행했다.', thumbFile: 'pc_yoonsieon_p1.png', detailPrefix: 'pe_yoonsieon_p1', imagesCount: 2, email: 'y.sieon.0218@gmail.com', insta: '@sieon_yoon' },
    { id: 'V_yoonsieon_2', category: 'Visual', designer: '윤시언', engName: 'YOON SIEON', title: '안산을 담은 젊은 와인 브랜드 "안산도"', desc: '안산도는 안산의 특산물인 대부 포도를 활용하여, 젊은 세대가 부담 없이 와인에 입문할 수 있도록 기획한 브랜드이다. 브랜드명은 안산, 와인의 중요 요소 \'산도\' , 함께 어울린다는 \'~도\'를 포함하여 만들어졌다. 함께 어울리고 안산에서 함께 와인을 마신다는 뜻이다. 안산도의 그래픽은 동그라미부터 별까지 다양한 도형이 사용된다. 이는 다양한 맛을 표현하는 시각적 이미지도 있지만, 다양한 사람들이 겹치기도 하고 또 겹치는 것을 표현하기도 하였다. 다른 사람들과 함께 어울리며 와인 한잔을 가볍게 즐기는 것이다.', thumbFile: 'pc_yoonsieon_p2.png', detailPrefix: 'pe_yoonsieon_p2', imagesCount: 2, email: 'y.sieon.0218@gmail.com', insta: '@sieon_yoon' },
    
    { id: 'V_leelime_1', category: 'Visual', designer: '이라임', engName: 'LEE LIME', title: 'AGAPE LAB', desc: '아가페 랩은 사랑을 인간의 삶을 구성하는 가장 핵심적인 필수 원소이자 건강 상태로 규정하는 연구소이다. 현대인이 겪는 만성 피로와 정서적 예민함, 대인관계 속 공격성의 원인을 ‘사랑 영양실조’ 상태로 정의했다. 7가지 사랑(에로스, 루두스, 스토르게, 마니아, 프라그마, 아가페, 필리아)에서 파생된 총 118개의 사랑 원소를 체계화했다. 유형별 개별 검사지를 통해 결핍된 원소와 부족한 양을 진단하여 영양 상태를 측정하고, 바닥난 사랑 성분을 채워 결핍을 치유할 수 있도록 맞춤형 솔루션을 처방한다.', thumbFile: 'pc_leelime_p1.png', detailPrefix: 'pe_leelime_p1', imagesCount: 2, email: 'Lime48k@gmail.com', insta: '@laim_ele' },
    { id: 'V_leelime_2', category: 'Visual', designer: '이라임', engName: 'LEE LIME', title: '읽it 페스티벌', desc: '읽잇 페스티벌은 단순히 정적으로 앉아 책을 읽는 형태에서 벗어나, 독서를 자신을 표현하는 수단이자 역동적인 놀이로 제안하는 북 페스티벌이다. ‘맛있게 소비하는 독서’, ‘온전히 몰입하는 독서’, ‘개성과 멋을 드러내는 독서’라는 세 가지 핵심 가치를 중심으로 감각적인 텍스트 경험을 설계했다. 서울광장에서 다양한 출판사 부스와 스티커 이벤트, 빈백에서 편안하게 책을 읽을 수 있는 존을 함께 구성했다. 관람객이 텍스트를 마음껏 즐기고 표현하며, 독서가 트렌디하고 힙한 놀이로 확장되는 축제의 장을 선보인다.', thumbFile: 'pc_leelime_p2.png', detailPrefix: 'pe_leelime_p2', imagesCount: 2, email: 'Lime48k@gmail.com', insta: '@laim_ele' },
    
    { id: 'V_leesemin_1', category: 'Visual', designer: '이세민', engName: 'LEE SEMIN', title: 'melty', desc: '브랜드명 Melty는 에너지가 소모되는 과정을 ‘녹아내림(Melting)’으로 시각화한 것에서 착안한 브랜드이다. 에너지의 소모를 배터리 잔량이 줄어드는 모습에 비유하여 브랜드 콘셉트로 발전시킨다. 에너지는 물리적, 인지적, 감정적, 사회적, 신경적, 디지털 에너지의 6가지로 분류한다. 각 에너지에는 직업적 특성과 성격을 부여하여 하나의 캐릭터로 제작한다. 또한 에너지가 점차 소모되는 과정을 단계적으로 녹아내리는 모습으로 표현하고, 배터리 잔량에 따라 변화하는 색상을 적용하여 에너지 소모의 흐름을 시각적으로 나타낸다.', thumbFile: 'pc_leesemin_p1.png', detailPrefix: 'pe_leesemin_p1', imagesCount: 2, email: 'leesemin0417@gmail.com', insta: '@sml_design_oo_' },
    { id: 'V_leesemin_2', category: 'Visual', designer: '이세민', engName: 'LEE SEMIN', title: 'MILMITER', desc: '본 프로젝트는 다양한 문화가 공존하는 동두천의 지역적 특성에서 착안하여 한국 음식을 전투식량 콘셉트로 재해석한 식품 브랜드이다. 외국인들이 한국 음식을 쉽고 흥미롭게 접할 수 있도록 기획하였으며, MILMITER는 Meal(식사)과 Meter(계기판, 측정기)를 결합한 이름으로, 소모된 에너지를 빠르게 충전하여 일상에 활력을 제공한다는 의미를 담는다. 카모플라주 패턴과 메뉴의 주재료를 활용하고, 주재료의 색상을 메뉴별 컬러로 적용하여 밀리터리 콘셉트와 메뉴의 특징을 시각적으로 표현하였다. 브랜드의 정체성을 강화하였다.', thumbFile: 'pc_leesemin_p2.png', detailPrefix: 'pe_leesemin_p2', imagesCount: 2, email: 'leesemin0417@gmail.com', insta: '@sml_design_oo_' },
    
    { id: 'V_leeyechan_1', category: 'Visual', designer: '이예찬', engName: 'LEE YECHAN', title: '행복', desc: '필리핀 톤도 선교에서 만난 이들과 함께 지내며, 그동안 스스로 정의해 온 행복의 한계를 돌아보게 됐다. 풍족하게 소유하는 것만이 행복이라고 생각했지만, 서로의 일상을 나누고 작은 기쁨을 함께하는 과정에서 진정한 행복을 발견할 수 있음을 깨달았다. 이번 작업은 이러한 경험과 감정을 시각화한 결과물이다. 마음을 전하는 엽서, 일상을 기록하는 달력, 선교지에서 느낀 벅찬 감정을 담은 포스터 시리즈로 구성했다. 이 작품을 통해 각자의 행복을 새롭게 발견하고, 주변의 사람들과 넉넉히 나눌 수 있기를 바란다.', thumbFile: 'pc_leeyechan_p1.png', detailPrefix: 'pe_leeyechan_p1', imagesCount: 2, email: 'dpcks7512@naver.com', insta: '@00owo00_' },
    { id: 'V_leeyechan_2', category: 'Visual', designer: '이예찬', engName: 'LEE YECHAN', title: '심폐소생고', desc: '일상에서 냉장고 속 식재료가 유통기한을 넘겨 방치되고, 결국 음식물 쓰레기로 버려지는 상황에 문제의식을 느껴 이 프로젝트를 시작했다. 소비되지 못한 채 버려지는 자원을 줄이고, 식재료를 보다 효율적이고 지속 가능하게 관리할 방법을 고민했다. 이에 식재료의 유통기한과 보관 상태를 한눈에 확인하고, 유통기한 임박 알림을 통해 사용 시점을 놓치지 않도록 돕는 관리 시스템을 디자인했다. 이를 통해 식재료의 소비를 자연스럽게 유도하고 올바른 관리 습관을 형성하여, 음식물 쓰레기를 줄이고 자원의 선순환에 기여하고자 했다.', thumbFile: 'pc_leeyechan_p2.png', detailPrefix: 'pe_leeyechan_p2', imagesCount: 2, email: 'dpcks7512@naver.com', insta: '@00owo00_' },
    
    { id: 'V_leejia_1', category: 'Visual', designer: '이지아', engName: 'LEE JIA', title: '0.6%', desc: '0.6%는 확률형 뽑기에서 원하는 결과물을 얻기 위해 게이머들이 반복하는 자신만의 의식과 행동에 주목한 프로젝트이다. 특정 장소나 시간, 뽑기 전의 습관 등 결과에 직접적인 영향이 없음에도 스스로 의미를 부여하며 실천하는 행위들을 수집했다. 바꿀 수 없는 정해진 확률 앞에서도 어떻게든 행운을 끌어당기려 했던 독특한 행동들을 시각적으로 풀어내어, 비합리적인 믿음에 기대서라도 원하는 결과를 얻고 싶었던 게이머들의 광적이면서도 순수한 기대를 보여주고자 한다. 특히 우연히 좋은 결과를 얻은 뒤 자신이 했던 행동을 다른 사람과 공유하는 모습에도 주목했다.', thumbFile: 'pc_leejia_p1.png', detailPrefix: 'pe_leejia_p1', imagesCount: 2, email: 'ji041018@gmail.com', insta: '@dl_.wldk' },
    { id: 'V_leejia_2', category: 'Visual', designer: '이지아', engName: 'LEE JIA', title: 'STATS', desc: '게임 속 캐릭터의 능력치를 통해 현재 상태와 필요한 요소를 확인하듯, STATS는 일상에서도 자신의 상태에 맞는 에너지를 선택하고 채우는 경험에 주목했다. 각 제품에 게임의 능력치 개념을 적용하고 맛과 색상, 패키지 디자인을 연결해 제품의 특징을 직관적으로 표현했다. 자신에게 필요한 능력치를 직접 고르고 채우는 과정을 게임에서 아이템을 선택하는 경험과 연결하여, 식품을 선택하는 순간에도 재미와 개성을 느낄 수 있도록 디자인했다. 이를 통해 일상적인 식품 선택에 게임의 재미를 더하고 새로운 경험을 제안하고자 했다.', thumbFile: 'pc_leejia_p2.png', detailPrefix: 'pe_leejia_p2', imagesCount: 2, email: 'ji041018@gmail.com', insta: '@dl_.wldk' },
    
    { id: 'V_limjungeun_1', category: 'Visual', designer: '임정은', engName: 'LIM JUNGEUN', title: 'OWN THE NOISE', desc: '록 음악 씬에서 여성은 오랫동안 주체보다 소재로 소비되어 왔다. &lt;OWN THE NOISE&gt;는 여성 록 뮤지션들의 주체적인 목소리와 음악에 주목하고, 앞으로의 행보를 응원하는 페스티벌이다. ‘소음을 스스로의 것으로 만든다’는 의미를 담아 여성 록 뮤지션이 무대를 주체적으로 이끄는 존재임을 표현한다. 페스티벌의 아이덴티티를 담은 홍보물과 굿즈를 제작하고, 서구와 한국의 여성 록 뮤지션을 시대별로 담은 아카이브 북을 구성해 여성들이 록 음악계에서 자신들의 활동 영역을 확장해 온 역사를 보여주고자 한다.', thumbFile: 'pc_limjungeun_p1.png', detailPrefix: 'pe_limjungeun_p1', imagesCount: 2, email: 'leemje16@naver.com', insta: '@leemjeun' },
    { id: 'V_limjungeun_2', category: 'Visual', designer: '임정은', engName: 'LIM JUNGEUN', title: '오밀조밀', desc: '토종곡물과 견과를 블렌딩해 식사의 밀도를 설계하는 곡물·견과 블렌딩 브랜드이다. 브랜드명 ‘오밀조밀’은 토종곡물과 견과처럼 작은 알갱이들이 모여 하나의 섬세한 식사를 만들어낸다는 의미를 담았다. 곡물과 견과의 비율을 8:2, 6:4, 4:6, 2:8의 네 가지 조합으로 구성하고, 다섯 가지 맛의 블렌드 라인을 제안한다. 곡물의 비율이 높은 제품은 파우더, 견과의 비율이 높은 제품은 스프레드로 구성하여 비율에 따른 밀도의 차이를 제품의 형태로 표현한다. 또한 여러 형태의 패키지를 구성하여 다양한 상황에서 즐길 수 있도록 한다.', thumbFile: 'pc_limjungeun_p2.png', detailPrefix: 'pe_limjungeun_p2', imagesCount: 2, email: 'leemje16@naver.com', insta: '@leemjeun' },
    
    { id: 'V_jeonminjeong_1', category: 'Visual', designer: '전민정', engName: 'JEON MINJEONG', title: '균사체 타이포그래피', desc: '이 프로젝트는 자연 속 피보나치 수열의 질서에서 발견한 균사체의 자기복제적 특성을 시각화한 작업이다. 균사체를 다루는 스튜디오를 운영하며, 대중에게 다소 어렵게 느껴질 수 있는 균사체의 정보를 누구나 흥미롭게 경험할 수 있도록 한다. 특히 자연의 기하학적 원리를 다양한 그래픽으로 치환하고 여러 매체를 통해 직관적으로 전달한다. 영상을 핵심 매체로 삼아 균사의 자기복제 과정을 보여주고, 이를 다시 책을 통해 확장하여 전달한다. 즉, 단순한 시각적 그래픽을 넘어 균사체 특징을 새로운 언어를 통해 보여주는 프로젝트이다.', thumbFile: 'pc_jeonminjeong_p1.png', detailPrefix: 'pe_jeonminjeong_p1', imagesCount: 2, email: 'djmj196022@naver.com', insta: '@m.j_jeon' },
    { id: 'V_jeonminjeong_2', category: 'Visual', designer: '전민정', engName: 'JEON MINJEONG', title: 'KEENK / KNEEK', desc: '이 프로젝트는 카페 방문을 즐기고 커피에 깊은 관심을 가진 경험에서 출발한다. \'KEENK / KNEEK\'은 러닝의 역동적인 에너지와 잘 어울리는 번개를 주요 모티브로 삼아 로고와 그래픽을 제작했다. 특히 러닝의 속도감과 다채로운 매력을 보여주기 위해 서로 다른 조합의 3가지 버전으로 디자인을 확장했으며, 각 버전에 맞춘 채도 높은 컬러 시스템을 적용해 더욱 시각적인 역동감을 보여주려고 했다. 단순한 휴식 공간을 넘어, 러너들이 일상 속에서 서로 소통하고 성취감을 공유하며 실질적인 혜택까지 누릴 수 있는 건강한 커뮤니티 브랜드를 제안하고자 한다.', thumbFile: 'pc_jeonminjeong_p2.png', detailPrefix: 'pe_jeonminjeong_p2', imagesCount: 2, email: 'djmj196022@naver.com', insta: '@m.j_jeon' },
    
    { id: 'V_jungseeun_1', category: 'Visual', designer: '정세은', engName: 'JUNG SEEUN', title: '맛의 형태', desc: '우리가 미각으로 느끼는 20가지의 맛을 눈에 보이는 형태로 시각화하여, 다채로운 재료와 요리의 매력을 깊이 있게 담아내는 프로젝트이다. 20가지 맛의 형태 포스터를 기준으로 재료들을 표현하였고, 그 재료 카드들을 조합하여 각 맛당 2개씩 총 40가지의 다채로운 요리 엽서를 완성했다. 또한 이런 맛있는 요리가 만들어지는 조리 과정을 모션 레시피 영상으로 제작하여 담아냈다. 사람들이 단순히 눈으로 보는 것만으로도 맛을 느낄 수 있도록, 추상적인 맛의 형태를 포스터와 카드, 영상 등 다양한 매체로 확장하여 새로운 시각적 미식의 즐거움을 전한다.', thumbFile: 'pc_jungseeun_p1.png', detailPrefix: 'pe_jungseeun_p1', imagesCount: 2, email: 'jdo256810@gmail.com', insta: '' },
    { id: 'V_jungseeun_2', category: 'Visual', designer: '정세은', engName: 'JUNG SEEUN', title: 'NEWS: 사방신 퍼포먼스 음료', desc: '동양철학의 사방신 기반 퍼포먼스 음료 브랜드로, 사방신이 관장하는 시간대에 소비자의 일상을 대입한 기능성 음료 브랜드이다. 청룡은 활기찬 에너지가 필요한 오전을, 주작은 에너지가 가장 뜨겁게 빛나는 낮을 책임지며, 백호는 하루의 피로를 진정시키는 저녁을, 현무는 깊은 휴식과 회복을 이끄는 새벽을 관장한다. 이처럼 소비자가 처한 시간과 상황에 따라 매 순간 최상의 컨디션을 유지할 수 있도록 설계되었으며, 단순한 음료를 넘어 현대인의 일상의 리듬을 바르게 잡아주는 건강한 하루 루틴을 선사하고자 한다.', thumbFile: 'pc_jungseeun_p2.png', detailPrefix: 'pe_jungseeun_p2', imagesCount: 2, email: 'jdo256810@gmail.com', insta: '' },
    
    { id: 'V_jeonghyeonhee_1', category: 'Visual', designer: '정현희', engName: 'JEONG HYEONHEE', title: '우연의 발견', desc: '이 프로젝트는 의도하지 않은 오류나 실수같은 \'예측 불가능한 우연’이 인류의 발명과 발견으로 이어진 순간들을 디자이너의 시선으로 기록하고 시각화하는 그래픽 아카이빙 프로젝트이다. 단순히 역사적 사실을 나열하는 방식에서 벗어나, 우연에 대한 사건 데이터를 나만의 방식으로 풀어내 작업에 담아냈다. 포스터는 줄글 설명이 아닌 그래픽적으로 재해석하여 한장에 시각적으로 표현했고, 아카이빙북은 추상화된 포스터를 해설하는 도록의 기능으로, 그 우연이 어떠한 사건을 통해 인류의 발견으로 전환되었는지 내부적인 맥락과 정보를 실제 이미지들과 함께 구성하여 작업했다.', thumbFile: 'pc_jeonghyeonhee_p1.png', detailPrefix: 'pe_jeonghyeonhee_p1', imagesCount: 2, email: 'hyunhee8988@gmail.com', insta: '@0217.hh' },
    { id: 'V_jeonghyeonhee_2', category: 'Visual', designer: '정현희', engName: 'JEONG HYEONHEE', title: '베이킹 재료 소분 배송 서비스 플랫폼 \'꼬집\'', desc: '\'꼬집\'은 홈 베이커들을 위한 재료 소분 배송 서비스 플랫폼이다. 대량 제작보다 소량 제작이 많은 홈 베이커들은 늘 필요 이상의 재료를 구매해야 하는 불편함이 있는데, 이러한 문제를 해결하기 위해 사용자가 원하는 베이킹 재료를 낭비없이 딱 필요한 만큼만 소분 배송을 받을 수 있도록 기획한 서비스이다. 베이킹이라는 주제에 맞춰 키컬러, 그래픽, 아이콘 등 전반적인 브랜드 아이덴티티를 파스텔톤의 따뜻하고, 귀여운 느낌으로 진행했다. 단순 패키지 상품이 아닌 ‘배송 서비스’이기 때문에, 패키지 디자인과 앱 디자인을 했다.', thumbFile: 'pc_jeonghyeonhee_p2.png', detailPrefix: 'pe_jeonghyeonhee_p2', imagesCount: 2, email: 'hyunhee8988@gmail.com', insta: '@0217.hh' },
    
    { id: 'V_joosungeun_1', category: 'Visual', designer: '주성은', engName: 'JOO SUNGEUN', title: 'FRAME ESCAPE', desc: 'FRAME ESCAPE는 책을 즐기고 싶지만, 책을 끝까지 읽어야 한다, 무언가를 배워야 한다 등의 압박감으로 인해 독서에 집중하지 못하는 사람들에게 새로운 독서 행동을 제안하여 독서에 대한 고정관념과 강박에서 벗어나 책 읽기의 즐거움을 찾도록 돕는 북페어이다. 이러한 강박의 틀을 깨고 자유로운 재미로 탈출한다는 기획 의도를 담아 FRAME ESCAPE로 이름을 정하였다. 틀에서 벗어나는 자유로운 형태의 레터링으로 북페어의 의미를 시각적으로 나타내고 지루한 이미지에서 탈피하고자 밝고 강한 색상을 적용해 디자인했다.', thumbFile: 'pc_joosungeun_p1.png', detailPrefix: 'pe_joosungeun_p1', imagesCount: 2, email: 'linajse@gmail.com', insta: '@sunge_1231' },
    { id: 'V_joosungeun_2', category: 'Visual', designer: '주성은', engName: 'JOO SUNGEUN', title: '서리담', desc: '서리담은 자신에게 필요한 기운을 고르고 상징적인 향을 피우는 행동을 통해 주변에 기운을 머무르게 하여 좋은 운을 더하는 인센스 브랜드이다. 제사나 의식에서 연기를 피우는 한국 전통과 사주의 오행을 연결하여 한국의 전통이 보이는 브랜드를 제작했다. 서리담은 좋은 일이 일어나고(瑞) 이로운(利) 기운을 태운다는(炎) 뜻으로 서리다와 비슷한 어감으로 브랜드 이름을 정했다. 연기가 피어오르는 형상을 이용해 브랜드 이름을 레터링하고 심볼을 제작했다. 운을 상징하는 각각의 향, 색, 동물로 나누어 그래픽을 디자인하고 전통 무늬와 함께 사용했다.', thumbFile: 'pc_joosungeun_p2.png', detailPrefix: 'pe_joosungeun_p2', imagesCount: 2, email: 'linajse@gmail.com', insta: '@sunge_1231' },
    
    { id: 'V_chaseongyun_1', category: 'Visual', designer: '차성윤', engName: 'CHA SEONGYUN', title: '고구려 단청 건축 복원 프로젝트', desc: '고구려 고분벽화 속에 표현된 단청과 건축 요소를 바탕으로 당시 건축의 모습을 추정하고 복원하는 프로젝트이다. 고구려인은 죽은 뒤에도 생전의 삶이 이어진다고 믿는 계세사상에 따라 무덤을 하나의 집이나 궁전처럼 조성했으며, 기둥·주두·소로·첨차·창방 등 실제 건축 부재와 다양한 색채와 문양을 표현하였다. 본 프로젝트는 고분벽화에 남겨진 건축 요소와 단청의 형태·색채·문양을 분석하고 관련 자료와 비교하여 고구려 건축의 구조와 장식 체계를 추정한다. 이를 바탕으로 복원도와 3D 모델을 제작하여 고구려 건축 공간을 시각적으로 재현하였다.', thumbFile: 'pc_chaseongyun_p1.png', detailPrefix: 'pe_chaseongyun_p1', imagesCount: 2, email: 'cwj2804@naver.com', insta: '' },
    { id: 'V_chaseongyun_2', category: 'Visual', designer: '차성윤', engName: 'CHA SEONGYUN', title: '담록', desc: '담록은 봄·여름·가을·겨울을 대표하는 제철 나물을 활용해 계절마다 다른 풍미를 지닌 전통주를 제안하는 프로젝트이다. 자연이 선사하는 식재료의 맛과 향을 계절의 흐름에 따라 담아내고, 이를 통해 우리 고유의 식문화와 전통주의 가치를 현대적으로 표현하고자 했다. 각각의 술에는 해당 계절의 나물이 지닌 고유한 특성과 풍미를 담아 한 잔의 술에서도 계절의 변화와 자연의 정취를 느낄 수 있도록 구성하였다. ‘담록’은 자연의 푸름과 생명력을 술에 담는다는 의미를 바탕으로, 전통과 현대가 조화를 이루는 새로운 전통주의 방향을 제시한다.', thumbFile: 'pc_chaseongyun_p2.png', detailPrefix: 'pe_chaseongyun_p2', imagesCount: 2, email: 'cwj2804@naver.com', insta: '' },
    
    { id: 'V_choijihyo_1', category: 'Visual', designer: '최지효', engName: 'CHOI JIHYO', title: '징크스', desc: '징크스(Jinx)는 불길한 징후와 불운을 뜻하며, 특별한 근거가 없음에도 특정한 행동이나 상황을 불운의 원인으로 연결하는 관념을 의미한다. 우리는 일상에서 우연히 일어난 사건에 의미 부여하고, 반복되는 경험을 하나의 규칙처럼 받아들이며 스스로 징크스를 만들어낸다. 본 작업은 이러한 징크스와 미신이 형성되는 과정에 주목하여, 일상 속 불안과 믿음이 어떻게 하나의 징크스로 자리 잡는지를 표현하였다. 포스터, 책, 부적이라는 세 가지 매체로 각각의 징크스가 가진 이야기와 상징을 전달하고, 익숙하게 받아들였던 미신을 새로운 시각에서 바라보며 작업하였다.', thumbFile: 'pc_choijihyo_p1.png', detailPrefix: 'pe_choijihyo_p1', imagesCount: 2, email: 'jihyo3127@naver.com', insta: '@jihyo3127' },
    { id: 'V_choijihyo_2', category: 'Visual', designer: '최지효', engName: 'CHOI JIHYO', title: '전통 괴담 향수', desc: '귀향(鬼香)은 귀신 귀(鬼)와 향기 향(香)을 결합하여, 괴담 속 존재들의 이야기를 향으로 담아낸다는 의미를 지닌 향수 브랜드이다. 한국의 괴담과 설화 속 존재들을 향으로 재해석하고, 각 9개의 괴담이 지닌 이야기와 분위기, 상징적인 요소를 분석하여 향의 조합과 그래픽으로 표현하였다. 익숙한 괴담을 시각적인 이미지에만 머무르지 않고 후각으로 경험할 수 있도록 확장하여, 이야기 속 공포와 신비로움을 각각의 향에 담아냈다. 또한 괴담의 특징을 패키지 그래픽에 적용하여 향수마다 서로 다른 분위기와 개성을 나타내며 작업하였다.', thumbFile: 'pc_choijihyo_p2.png', detailPrefix: 'pe_choijihyo_p2', imagesCount: 2, email: 'jihyo3127@naver.com', insta: '@jihyo3127' },
    
    { id: 'V_choihyoju_1', category: 'Visual', designer: '최효주', engName: 'CHOI HYOJU', title: 'ANIMA', desc: 'ANIMA(아니마)는 동물 캐릭터들의 따뜻하고 유쾌한 일상을 담아낸 소품 브랜드이다. 활기찬 토끼 릴리, 자유로운 고양이 찰리, 차분한 강아지 샐리는 서로 다른 매력으로 자신들만의 이야기를 만들어간다. 세 캐릭터와 주변 동물 친구들이 함께하는 다채로운 에피소드는 일상에서 쉽게 사용할 수 있는 문구, 생활 소품 등 다양한 굿즈로 확장된다. 아니마는 단순한 캐릭터 상품 이상의 의미를 지닌다. 작고 사랑스러운 물건을 통해 사용자에게 일상 속 소소한 즐거움과 따뜻한 감정을 선물하고 행복함을 더해주는 브랜드이다.', thumbFile: 'pc_choihyoju_p1.png', detailPrefix: 'pe_choihyoju_p1', imagesCount: 2, email: 'hyojuchoi0216@gmail.com', insta: '' },
    { id: 'V_choihyoju_2', category: 'Visual', designer: '최효주', engName: 'CHOI HYOJU', title: 'BOUT', desc: 'BOUT(바우트)는 누구나 안전하고 편리하게 복싱 스파링을 즐길 수 있도록 설계된 맞춤형 대전 플랫폼이다. 사용자의 체급과 실력 정보를 바탕으로 가장 적합한 상대를 연결한다. 두 명의 복서와 한 명의 심판이 동시에 매칭되는 시스템을 통해 스파링 중 발생할 수 있는 사고를 방지하고 대전의 안전성을 확보한다. 매칭이 성사된 후에는 채팅을 통해 일정과 경기 규칙을 사전에 조율할 수 있다. 위치 기반 서비스로 가까운 체육관과 링 대관 정보를 빠르게 탐색할 수 있도록 지원하여 복서가 신뢰할 수 있는 환경에서 스파링에 집중하도록 돕는다.', thumbFile: 'pc_choihyoju_p2.png', detailPrefix: 'pe_choihyoju_p2', imagesCount: 2, email: 'hyojuchoi0216@gmail.com', insta: '' },

    // ==========================================
    // Space (15명 x 1작품 = 15개)
    // ==========================================
    { id: 'S_kimryeongik', category: 'Space', designer: '김령익', engName: 'KIM RYEONGIK', title: '여여선원(如如禪院)', desc: '‘여(如)’는 그러하다, ‘여여(如如)’는 그러하고 그러하다는 뜻이다. 여여선원은 언덕의 경사와 지형을 있는 그대로 받아들이며, 그 위에 사찰의 공간 질서를 새롭게 담아낸다. 높은 경사와 낙후된 산책로로 접근성이 떨어지는 기존 언덕에 보행의 흐름을 재구성하고, 산책로와 건축물의 배치와 높이를 통해 세속에서 수행으로 나아가는 공간적 위계를 형성한다. 자연을 지우고 건축을 세우는 것이 아니라, 본래의 모습을 존중하며 그 안에 공동체와 수행의 공간을 놓는다. 여여선원(如如禪院)은 지형과 건축, 움직임과 멈춤이 자연스럽게 공존하는 사찰을 제안한다.', thumbFile: 'pc_kimryeongik.png', detailPrefix: 'pe_kimryeongik', imagesCount: 2, email: 'rungrick02@gmail.com', insta: '' },
    { id: 'S_kimseungmin', category: 'Space', designer: '김승민', engName: 'KIM SEUNGMIN', title: 'Pakr in Memorial', desc: '도시의 변방으로 추방된 추모 공간과 공동화 현상으로 비워져 가는 대구 도심은 \'단절과 소외\'라는 도시적 맥락을 공유한다. 본 프로젝트는 쇠퇴하는 도심의 유휴 공간을 회복의 매개체로 삼아, 고립되었던 추모시설을 일상의 영역으로 연결하는 작업이다. 기피의 대상이었던 죽음의 공간을 문화, 휴식, 추모가 어우러진 열린 공공 공간으로 전환하여 시민들이 자연스럽게 머물고 기억할 수 있도록 구성했다. 이를 통해 도시 중심부의 장소성을 되살리고, 삶과 죽음이 도시 조직 안에서 자연스럽게 순환하는 입체적인 대안을 제시한다.', thumbFile: 'pc_kimseungmin.png', detailPrefix: 'pe_kimseungmin', imagesCount: 2, email: 'kimsc0715@naver.com', insta: '@tmdals_kim__' },
    { id: 'S_namihyeon', category: 'Space', designer: '나미현', engName: 'NA MIHYEON', title: 'IN PROGRESS : 청년 창업 플랫폼', desc: '이 프로젝트는 청년 창업가들이 길음청년창업거리에 진출하기 전, 아이디어를 실험하고 검증하는 중간 플랫폼이다. 완성되지 않은 창업의 과정처럼 건축 역시 고정된 형태가 아니라 필요에 따라 변화하고 확장된다. 고정된 프레임 안에는 전시, 판매, 메이커, 주거, 회의 등의 가변형 모듈이 삽입되며, 프로그램은 추가·제거되고 활동은 광장과 외부로 확장된다. 비워진 프레임은 새로운 가능성을 담는 성장의 여지로 남는다. 센터 안의 경험, 제작, 거주는 독립과 길음청년창업거리로의 확장으로 이어지고, 다시 새로운 창업가와 활동이 유입되며 지속적인 순환을 만든다.', thumbFile: 'pc_namihyeon.png', detailPrefix: 'pe_namihyeon', imagesCount: 2, email: 'mihyun203@naver.com', insta: '@vr.nuyhim' },
    { id: 'S_parkhyunsoo', category: 'Space', designer: '박현수', engName: 'PARK HYUNSOO', title: 'SONANCE COMMONS', desc: '혜화는 오랫동안 소극장과 연극을 중심으로 다양한 문화가 쌓여온 공간이지만, 최근 극장 수의 감소로 그 고유한 분위기가 약해지고 있다. 본 프로젝트는 혜화의 연극 문화를 이어가기 위해 공연장과 광장을 결합한 문화공간을 제안한다. 특정 시간에만 방문하는 극장이 아니라 사람들이 걷고 머물며 공연을 마주하는 일상의 공간을 만들고자 했다. 광장을 중심으로 실내 소극장과 야외 공연, 휴식과 교류의 공간을 연결해 사람과 공연이 만나는 흐름을 계획했다. 이를 통해 혜화의 공연 문화를 다시 도시의 일상 속으로 끌어들이고 만남과 경험이 이어지는 장소를 제안한다.', thumbFile: 'pc_parkhyunsoo.png', detailPrefix: 'pe_parkhyunsoo', imagesCount: 2, email: 'eunhyun0107@naver.com', insta: '@c_f_g4' },
    { id: 'S_sonminsu', category: 'Space', designer: '손민수', engName: 'SON MINSU', title: 'The Maze of Light : In the Runway', desc: '고층 빌딩과 빠른 소비가 지배하는 효율 중심의 강남에 다양한 모듈 사이로 공간을 만들고 동선을 연결하여 현대적인 미로를 조성하여 탐험하듯 의도적으로 길을 잃으며 브랜드를 마주하는 느린 쇼핑을 유도한다. 바닥과 계단을 가로지르는 유도 조명과 미로 공간들은 보행자를 런웨이 위를 걷는 모델처럼 보이도록 연출해 건물 자체를 런웨이 무대로 완성한다. 빛의 길이 있는 거대한 지붕과 입면의 유리를 통해 강남의 빛을 반사하고 확산시키며 공해로 느껴질 수 있는 빛을 건물의 요소로 전환해준다. 이를 통해 빛의 미로 속에서 머무름과 느린 휴식을 경험한다.', thumbFile: 'pc_sonminsu.png', detailPrefix: 'pe_sonminsu', imagesCount: 2, email: 'hoopozero@naver.com', insta: '' },
    { id: 'S_ohjinwoo', category: 'Space', designer: '오진우', engName: 'OH JINWOO', title: 'Chrono Lumen', desc: '남산예장공원의 지하 보행로는 아픈 역사의 레이어가 지하 어둠 속에 침전된 장소입니다. 본 작품은 지면의 개구부와 굴뚝 형상의 수직 보이드 구조체를 활용하여, 무형의 시간을 실체적인 빛의 흐름으로 반전시킵니다. 보이드가 지하 깊이 끌어들인 강렬한 빛은 이 공간을 지나는 이들을 과거의 어둠에서 현재로 이끄는 여정으로 안내합니다. 태양의 고도에 따라 벽면을 훑는 빛의 궤적은 잊혀가던 남산의 역사적 단면을 조명합니다. 빛과 어둠이 교차하는 수직 보이드 속에서 남산의 역사가 현재의 빛과 호흡하는 순간의 경험에 집중하였습니다.', thumbFile: 'pc_ohjinwoo.png', detailPrefix: 'pe_ohjinwoo', imagesCount: 2, email: 'ebada0486@naver.com', insta: '@jwz5_1' },
    { id: 'S_jeonseongmin', category: 'Space', designer: '전성민', engName: 'JEON SEONGMIN', title: '하나에서 여럿으로 : 숲속 웰니스 플랫폼', desc: '속도 중심 사회의 압박감은 일상의 번아웃으로 이어졌고, 필수 시설인 적환장은 기피 시설로서 주변 환경과 단절되어 왔다. 본 프로젝트는 기존 적환장 기능을 지하화하여 필수 인프라를 유지하되, 지상부에는 심리적 문턱을 낮춘 일상적인 치유 인프라를 구축해 도시와 개인의 피로를 동시에 해소하고자 한다. 물방울이 분열하듯 전개되는 공간은 진입부의 거대한 공공 문화 영역에서 시작해 점차 숲속 깊은 곳에 자리한 독립된 개인 휴식 영역으로 이어진다. 이를 통해 공공의 교류에서 개인의 온전한 쉼으로 나아가는 점진적인 공간의 변화를 만들어낸다.', thumbFile: 'pc_jeonseongmin.png', detailPrefix: 'pe_jeonseongmin', imagesCount: 2, email: 'wjstjdals0421@gmail.com', insta: '@m_i_n_0421' },
    { id: 'S_jungwonji', category: 'Space', designer: '정원지', engName: 'JUNG WONJI', title: '숲잇길', desc: '본 프로젝트는 서울숲 일대의 심각한 주차 부족 문제를 해소함과 동시에, 카페거리와 서울숲을 잇는 동선상에 독서라는 비일상적 경험을 삽입하여 도시의 단절을 해소한다. 층별 주제에 맞춘 깊이 있는 도서 큐레이션을 적용하여, 방문객이 자연스럽게 책과 도시를 관조하도록 설계하였다. 건물 내부로 이어지는 개방적인 동선은 도서 라운지와 사운드 오브 북스 등 다채로운 프로그램으로 자연스럽게 스며든다. 이 공간은 단순한 서가를 넘어 일상 속에 영감을 채우는 지적인 산책로가 되며, 도시의 길과 사람을 하나로 엮어내는 성수의 새로운 문화적 거점으로 자리 잡는다.', thumbFile: 'pc_jungwonji.png', detailPrefix: 'pe_jungwonji', imagesCount: 2, email: 'wonji0249@gmail.com', insta: '@dnjs._.z' },
    { id: 'S_josungmin', category: 'Space', designer: '조성민', engName: 'JO SUNGMIN', title: '회연(會緣) - 세대와 삶을 잇는 생애전환 플랫폼', desc: '신림동은 고시촌에서 청년창업 중심지로 빠르게 변화했지만, 그 과정에서 지역에 정착하지 못한 청년과 기존 거주민 사이의 단절이 남았다. 대상지는 신림역과 서원역 사이, 별빛내린천과 주거지를 잇는 높은 유동의 통과 공간이다. 본 프로젝트는 이 흐름을 건물 안으로 끌어들여 배움, 제작, 수선, 기록과 휴식이 이어지는 복합문화공간으로 전환한다. 서로 다른 이용자의 동선은 램프와 단차를 따라 교차하며 경험과 기술을 나누고 관계를 형성한다. 빠르게 지나가던 도시의 흐름 속에 천천히 머물며 서로를 발견할 수 있는 새로운 지역적 기반을 제안한다.', thumbFile: 'pc_josungmin.png', detailPrefix: 'pe_josungmin', imagesCount: 2, email: 'eol6012@hanmail.net', insta: '@su.ngmin_' },
    { id: 'S_chohyeryeong', category: 'Space', designer: '조혜령', engName: 'CHO HYERYEONG', title: '대선상회: Layers of Daesun', desc: '영등포 대선제분은 과거 산업화의 흐름과 당시 생활의 기억이 중첩된 장소이다. 본 프로젝트는 기존 공장 내부의 급격한 변형보다, 인입선의 흔적과 기능에 따라 형성된 공장의 축, 인접한 영일시장과 주변 동선을 바탕으로 장소에 남겨진 흔적을 재조직하는 방식에 주목한다. 또한 공장 곳곳에 덧대어지고 축적된 비정형의 형태들을 장소의 시간성으로 보고, 불안정한 구조는 보강하되 새로운 요소를 더해 앞으로도 쌓여갈 시간적 층위를 드러낸다. 이러한 해석을 바탕으로 대선제분을 건강한 곡물 문화를 실험하는 곡물 전환 플랫폼으로 재구성한다.', thumbFile: 'pc_chohyeryeong.png', detailPrefix: 'pe_chohyeryeong', imagesCount: 2, email: '5467cho@gmail.com', insta: '@h._ryeong' },
    { id: 'S_chamuyoung', category: 'Space', designer: '차무영', engName: 'CHA MUYOUNG', title: '난지, 녹색 이후 : 윤회', desc: '난지도는 쓰레기를 매립한 땅 위에 공원이 조성되며 도시가 외면해 온 폐기물의 흔적을 녹색으로 덮어온 장소이다. 「난지 녹색 이후」는 이러한 장소의 역사에서 출발해, 소각장을 다시 도시의 일상과 연결하는 방식을 제안한다. 단절된 지형과 동선을 브릿지로 잇고, 에코리움을 통해 시민이 시설을 이동과 체험 속에서 자연스럽게 마주하도록 한다. 폐기물 처리 시설을 감추거나 밀어내는 대신 도시의 순환을 이루는 하나의 과정으로 드러내며, 소비와 폐기, 처리와 재생이 다시 이어지는 새로운 난지도의 풍경을 만든다.', thumbFile: 'pc_chamuyoung.png', detailPrefix: 'pe_chamuyoung', imagesCount: 2, email: 'mycha924@gmail.com', insta: '@chamu_0' },
    { id: 'S_choiminho', category: 'Space', designer: '최민호', engName: 'CHO MINHO', title: '사색의 정원', desc: '신촌민자역사는 상권 침체와 긴 배차 간격, 철도와 역사로 인한 남북 및 이대 운동장과의 보행 단절 문제를 겪고 있다. \'사색의 정원\'은 대학생들을 위한 컨벤션센터, 주민과 유동 인구를 위한 커뮤니티 문화센터, 다채로운 액티비티 센터를 도입하여 끊어진 도시의 흐름을 다시 잇는다. 프로그램들 사이에 유기적으로 조성된 네 가지 콘셉트의 정원은 사람들의 자연스러운 발걸음과 체류를 유도한다. 이곳은 단순한 통과 공간을 넘어, 일상 속에서 편안하게 머물고 교류하며 사색을 즐기는 열린 도시 복합 공간으로 기능한다.', thumbFile: 'pc_choiminho.png', detailPrefix: 'pe_choiminho', imagesCount: 2, email: 'chlalsgh0603@naver.com', insta: '@mino__choi' },
    { id: 'S_choieunhye', category: 'Space', designer: '최은혜', engName: 'CHOI EUNHYE', title: '잊다, 잇다, 있다', desc: '도봉구 방학동에 위치한 도깨비 시장은 오랫동안 존재해왔던 시장임에도 불구하고 동네 주민들만 이용하며 고립되어 있었다. 그뿐만 아니라 서울시 전체에서 주민 4명 중 1명이 이동 약자라는 특징을 가진 사이트이다. 이 프로젝트는 폐쇄적인 시장 구조를 유기적으로 연결하여, 미래에는 시장의 활기찬 흐름이 골목 사이사이로 스며들어 거대한 전통시장 플랫폼이 되는 것을 최종 목표로 삼는다. 아울러 이동 약자와 일반 사람들의 물리적·심리적 경계를 완전히 허물어, 모두가 같은 공간에서 동등한 경험을 누리도록 설계했다.', thumbFile: 'pc_choieunhye.png', detailPrefix: 'pe_choieunhye', imagesCount: 2, email: 'choieunhye0317@naver.com', insta: '@pgsmd.lhc' },
    { id: 'S_pyunminji', category: 'Space', designer: '편민지', engName: 'PYUN MINJI', title: '겹쳐진 일상을 따라,', desc: '철원 갈말읍은 농업 생산지가 주거지와 상업시설, 생활 동선 가까이에 맞닿아 있는 도농복합지역이다. 본 프로젝트는 이러한 주변 환경과 일상의 관계에 주목해, 지역을 대표하는 오대쌀을 매개로 생산과 체험, 가공과 소비가 하나의 흐름으로 이어지는 공간을 제안한다. 대지 주변의 생활 동선과 자연스럽게 연결되는 보행 흐름을 만들고, 재배 공간과 테라스, 다양한 프로그램을 배치해 주민과 방문객의 일상이 공간 안에서 겹쳐지도록 하였다. 이를 통해 농업이 일상과 분리된 생산의 영역이 아니라 지역의 삶과 함께 공유되고 확장되는 도농복합 플랫폼을 만들고자 한다.', thumbFile: 'pc_pyunminji.png', detailPrefix: 'pe_pyunminji', imagesCount: 2, email: 'happyday3962@gmail.com', insta: '@mz_ini_' },
    { id: 'S_hayueun', category: 'Space', designer: '하유은', engName: 'HA YUEUN', title: '결(結)의 접점', desc: '충현동에 위치한 복합문화시설 ‘결(結)의 접점’은 재개발 단지 북아현동과 상업 중심 지역 충정로 사이에 위치하여, 고립된 충현동의 흐름을 활성화시키는 중요한 경계이다. 단절된 공간을 자연스럽게 연결하기 위해 코어 프로그램인 벼룩시장을 통해 주변 골목의 동선을 내부로 끌어들여 입체적 교차를 가능하게 하였고, 사람들이 모여 소통하는 노드로 작용한다. 본 작품 ‘결(結)의 접점’은 이처럼 흩어진 골목의 결이 한데 모여 강력한 맺음을 이루는 공간이다. 이곳은 오랜 고립을 극복하고, 생성된 에너지가 다시 도시 전체로 퍼져나가는 연결의 정점이 된다.', thumbFile: 'pc_hayueun.png', detailPrefix: 'pe_hayueun', imagesCount: 2, email: 'hayuyu117@gmail.com', insta: '@yuuuueun.ii' }
];

/* 연도별 배경색 추가 */
const archiveDataset = [
    { year: 2025, format: 'png', link: 'http://gsdd.org/2025/index.html', title: 'CUT! LAYER! PASTE!', desc: '2025년도 전시 설명 내용...', bgColor: '#F6A700' },
    { year: 2024, format: 'webp', link: 'http://gsdd.org/2024/index.html', title: 'Get A Clue', desc: '대학에서의 4년간, 우리는 수많은 도전을 통해 많은 것을 배웠습니다. 이 과정에서 얻은 경험과 노력이 우리 미래에 대한 중요한 단서를 제공해 주었습니다. “GET A CLUE”는 이러한 경험을 바탕으로, 미래를 향한 방향성을 탐색하는 여정을 선보입니다.', bgColor: '#E72F4C' },
    { year: 2023, format: 'png', link: 'http://gsdd.org/2023/index.html', title: 'PROJECT: FUTUREFORMING', desc: '퓨처포밍 프로젝트는 학생들이 각자 광활한 우주로 나아가 별을 찾고, 미래에 정착할 수 있도록 포밍(forming) 시키는 프로젝트다. 졸업 전시를 통해 각자의 미래를 준비하고 모습을 만들어 가는 것을 원석을 깎아 별 조각으로 만드는 것으로 비유하였으며, 별 조각이 대 학생들의 작업물이 하나로 합쳐져 완전한 별 형태를 이룬다. 이는 우리의 미래 가능성을 보여주는 코어로 재현된다. 프로젝트의 성공은 전시장에 포밍 완료된 별 조각 샘플을 채취하여 전시하는 것으로 증명한다.', bgColor: '#009DDA' },
    { year: 2022, format: 'jpeg', link: 'http://gsdd.org/2022/', title: 'NEXT LEVEL', desc: '대학교 4학년의 마지막을 장식하는 졸업전시회는 곧 우리가 사회에 한 걸음 내딛게 된다는 사실을 알려줍니다. 우리는 졸업이라는 과정을 거쳐 학생에서 사회인으로 발전하게 되고, 이렇게 사회 생활이라는 새로운 단계로 넘어가게 됩니다. 학생들은 개개인만의 개성과 능력으로 작품을 만들고, 주어진 다음 단계를 스스로 풀어나간다는 의미를 담았습니다.', bgColor: '#14A146' },
    { year: 2021, format: 'png', link: 'http://gsdd.org/2021/', title: '2021', desc: '우리는 일상 속에서 디자인을 공부할 때 혹은 공책을 펴볼 때도 쉽게 행과 열을 찾아볼 수 있다. 각기 다른 행과 열이 뻗어 나가면 그 방향성이 모여 하나의 구조를 만들어내고 그 구조 안에는 다양한 가능성이 존재한다. 이는 우리와 닮아있다. 각자의 방식, 각자의 과정과 방법론이 모여 졸업전시회라는 구조를 만들어낸다.', bgColor: '#AAA1CE' },
    { year: 2020, format: 'webp', link: 'http://gsdd.org/2020/', title: '2020', desc: '지난 1월 유행하기 시작한 전염병 코로나로 인해 학교 출입 시, 마스크에 체온 확인 완료를 표시하기 위해 스티 차를 붙여야만 했다. 둥근 모양의 형광 스티커는 매일 다른 색으로 교체되었고 버려지거나 핸드폰, 노트북, 방 거울 등에 쌓여갔다. 형형색색의 스티커는 곧 코로나로 인해 바뀌어버린 우리의 생활을 뜻하기도 하지만 둥글둥글 귀여운 모양으로 핸드폰 뒷면에 남아있기도 했다. 우리는 둥근 스티커로 졸업생 한 명 한 명의 개성을 표현하고자 했다.', bgColor: '#EA5703' },
    { year: 2019, format: 'webp', link: 'http://gsdd.org/2019/', title: '2019', desc: '제 1회 동양대학교 디자인학부 졸업전시회', bgColor: '#0068AD' }
];